services:
  app:
    container_name: "glpi"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
    ports:
      - "8080:80"
      - "9637:9637"
    extra_hosts:
      - "host.docker.internal:host-gateway"
